#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require File.join(File.dirname(__FILE__), 'hbase_types')

        module Apache
          module Hadoop
            module Hbase
              module Thrift
      end
    end
  end
end
